# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
        fail_fast: true
    -   id: end-of-file-fixer
        fail_fast: true
    -   id: check-yaml
        fail_fast: true
    -   id: check-added-large-files
        fail_fast: true
- repo: local
  hooks:
    - id: ruff-check
      name: ruff check
      entry: ruff check --force-exclude
      language: system
      types_or: [python, pyi]
      require_serial: true
      fail_fast: true
      args: [--fix]
    - id: ruff-format
      name: ruff format
      entry: ruff format --force-exclude
      language: system
      types_or: [python, pyi]
      require_serial: true
      fail_fast: true
    - id: ty
      name: ty check
      entry: ty check
      language: system
      types_or: [python, pyi]
      fail_fast: true
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.9.17
  hooks:
    - id: uv-lock
    - id: uv-sync
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest --color=yes -m=''
      language: system
      pass_filenames: false
      always_run: true
      verbose: true
